// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkPSHAs0sPPx-2iAl_APzquIQXF0X9Geo',
    appId: '1:1046501087671:android:873511e2606cec1ab83032',
    messagingSenderId: '1046501087671',
    projectId: 'auth-72203',
    storageBucket: 'auth-72203.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw77vzKOpBg8Z285RxIc67Y2gByDfs_wg',
    appId: '1:1046501087671:ios:5146921f4560a885b83032',
    messagingSenderId: '1046501087671',
    projectId: 'auth-72203',
    storageBucket: 'auth-72203.appspot.com',
    androidClientId: '1046501087671-hk8los2mqmjq54qtjgoj46q19c0on7kn.apps.googleusercontent.com',
    iosClientId: '1046501087671-gnb55fnv122jrod4p1uso0j107houacn.apps.googleusercontent.com',
    iosBundleId: 'com.mightytaxirider.app',
  );

}